In [1]:
import  pandas as pd
import numpy  as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.linear_model import LogisticRegression  
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score
from sklearn.model_selection import train_test_split,GridSearchCV,RandomizedSearchCV

from sklearn.ensemble import RandomForestClassifier,AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier

from scipy.stats import zscore

In [2]:
df=pd.read_csv(r"C:\Users\mahes\OneDrive\Desktop\python\Datasets\bank-full.csv",delimiter=";")
df

age           job   marital  education default  balance housing loan  \
0       58    management   married   tertiary      no     2143     yes   no   
1       44    technician    single  secondary      no       29     yes   no   
2       33  entrepreneur   married  secondary      no        2     yes  yes   
3       47   blue-collar   married    unknown      no     1506     yes   no   
4       33       unknown    single    unknown      no        1      no   no   
...    ...           ...       ...        ...     ...      ...     ...  ...   
45206   51    technician   married   tertiary      no      825      no   no   
45207   71       retired  divorced    primary      no     1729      no   no   
45208   72       retired   married  secondary      no     5715      no   no   
45209   57   blue-collar   married  secondary      no      668      no   no   
45210   37  entrepreneur   married  secondary      no     2971      no   no   

         contact  day month  duration  campaign  pdays  previous poutcome    y  
0        unknown    5   may       261         1     -1         0  unknown   no  
1        unknown    5   may       151         1     -1         0  unknown   no  
2        unknown    5   may        76         1     -1         0  unknown   no  
3        unknown    5   may        92         1     -1         0  unknown   no  
4        unknown    5   may       198         1     -1         0  unknown   no  
...          ...  ...   ...       ...       ...    ...       ...      ...  ...  
45206   cellular   17   nov       977         3     -1         0  unknown  yes  
45207   cellular   17   nov       456         2     -1         0  unknown  yes  
45208   cellular   17   nov      1127         5    184         3  success  yes  
45209  telephone   17   nov       508         4     -1         0  unknown   no  
45210   cellular   17   nov       361         2    188        11    other   no  

[45211 rows x 17 columns]

In [3]:
df.describe()

age        balance           day      duration      campaign  \
count  45211.000000   45211.000000  45211.000000  45211.000000  45211.000000   
mean      40.936210    1362.272058     15.806419    258.163080      2.763841   
std       10.618762    3044.765829      8.322476    257.527812      3.098021   
min       18.000000   -8019.000000      1.000000      0.000000      1.000000   
25%       33.000000      72.000000      8.000000    103.000000      1.000000   
50%       39.000000     448.000000     16.000000    180.000000      2.000000   
75%       48.000000    1428.000000     21.000000    319.000000      3.000000   
max       95.000000  102127.000000     31.000000   4918.000000     63.000000   

              pdays      previous  
count  45211.000000  45211.000000  
mean      40.197828      0.580323  
std      100.128746      2.303441  
min       -1.000000      0.000000  
25%       -1.000000      0.000000  
50%       -1.000000      0.000000  
75%       -1.000000      0.000000  
max      871.000000    275.000000

In [4]:
z_score=zscore(df["age"])
threshold=3
index=np.where(np.abs(z_score)> threshold)
index

(array([29158, 29261, 29263, 29322, 29865, 30908, 31051, 31055, 31069,
        31089, 31099, 31101, 31116, 31125, 31130, 31145, 31151, 31183,
        31189, 31233, 31261, 31285, 31341, 31365, 31383, 31393, 31395,
        31414, 31447, 31527, 31569, 31647, 32009, 32032, 32064, 32068,
        32074, 32089, 32105, 32160, 32321, 32451, 32689, 32699, 33017,
        33360, 33414, 33455, 33699, 33706, 33719, 33751, 33752, 33766,
        33775, 33777, 33780, 33810, 33846, 33860, 34128, 40363, 40367,
        40368, 40374, 40389, 40402, 40412, 40481, 40515, 40524, 40538,
        40561, 40569, 40571, 40595, 40621, 40645, 40655, 40657, 40674,
        40676, 40710, 40712, 40726, 40759, 40786, 40792, 40816, 40838,
        40843, 40864, 40872, 40896, 40910, 40913, 40932, 40947, 40954,
        40978, 40987, 41007, 41036, 41099, 41101, 41104, 41136, 41162,
        41171, 41179, 41183, 41197, 41257, 41290, 41291, 41346, 41352,
        41376, 41387, 41406, 41423, 41439, 41448, 41469, 41470, 41505,
      

In [5]:
df=pd.get_dummies(df,columns=['job'],drop_first=True)

In [6]:
df

age   marital  education default  balance housing loan    contact  day  \
0       58   married   tertiary      no     2143     yes   no    unknown    5   
1       44    single  secondary      no       29     yes   no    unknown    5   
2       33   married  secondary      no        2     yes  yes    unknown    5   
3       47   married    unknown      no     1506     yes   no    unknown    5   
4       33    single    unknown      no        1      no   no    unknown    5   
...    ...       ...        ...     ...      ...     ...  ...        ...  ...   
45206   51   married   tertiary      no      825      no   no   cellular   17   
45207   71  divorced    primary      no     1729      no   no   cellular   17   
45208   72   married  secondary      no     5715      no   no   cellular   17   
45209   57   married  secondary      no      668      no   no  telephone   17   
45210   37   married  secondary      no     2971      no   no   cellular   17   

      month  ...  job_entrepreneur  job_housemaid  job_management  \
0       may  ...                 0              0               1   
1       may  ...                 0              0               0   
2       may  ...                 1              0               0   
3       may  ...                 0              0               0   
4       may  ...                 0              0               0   
...     ...  ...               ...            ...             ...   
45206   nov  ...                 0              0               0   
45207   nov  ...                 0              0               0   
45208   nov  ...                 0              0               0   
45209   nov  ...                 0              0               0   
45210   nov  ...                 1              0               0   

       job_retired job_self-employed job_services  job_student  \
0                0                 0            0            0   
1                0                 0            0            0   
2                0                 0            0            0   
3                0                 0            0            0   
4                0                 0            0            0   
...            ...               ...          ...          ...   
45206            0                 0            0            0   
45207            1                 0            0            0   
45208            1                 0            0            0   
45209            0                 0            0            0   
45210            0                 0            0            0   

       job_technician  job_unemployed  job_unknown  
0                   0               0            0  
1                   1               0            0  
2                   0               0            0  
3                   0               0            0  
4                   0               0            1  
...               ...             ...          ...  
45206               1               0            0  
45207               0               0            0  
45208               0               0            0  
45209               0               0            0  
45210               0               0            0  

[45211 rows x 27 columns]

In [7]:
df['education'].value_counts().to_dict()

{'secondary': 23202, 'tertiary': 13301, 'primary': 6851, 'unknown': 1857}

In [8]:
df['education'].replace({'secondary': 2, 'tertiary': 3, 'primary': 1, 'unknown': 0},inplace=True)

In [9]:
df['default'].value_counts().to_dict()

{'no': 44396, 'yes': 815}

In [10]:
df['default'].replace({'no': 0, 'yes': 1},inplace=True)

In [11]:
df['housing'].value_counts().to_dict()

{'yes': 25130, 'no': 20081}

In [12]:
df['housing'].replace({'yes': 1, 'no': 0},inplace=True)


In [13]:
df['loan'].value_counts().to_dict()

{'no': 37967, 'yes': 7244}

In [14]:
df['loan'].replace({'no': 0, 'yes': 1},inplace=True)

In [15]:
df['contact'].value_counts().to_dict()

{'cellular': 29285, 'unknown': 13020, 'telephone': 2906}

In [16]:
df['contact'].replace({'cellular': 1, 'unknown': 0, 'telephone': 2},inplace=True)

In [17]:
df=pd.get_dummies(df,columns=['month'],drop_first=True)

In [18]:
df['marital'].value_counts().to_dict()

{'married': 27214, 'single': 12790, 'divorced': 5207}

In [19]:
df['marital'].replace({'married': 1, 'single': 0, 'divorced': 2},inplace=True)

In [20]:
df

age  marital  education  default  balance  housing  loan  contact  day  \
0       58        1          3        0     2143        1     0        0    5   
1       44        0          2        0       29        1     0        0    5   
2       33        1          2        0        2        1     1        0    5   
3       47        1          0        0     1506        1     0        0    5   
4       33        0          0        0        1        0     0        0    5   
...    ...      ...        ...      ...      ...      ...   ...      ...  ...   
45206   51        1          3        0      825        0     0        1   17   
45207   71        2          1        0     1729        0     0        1   17   
45208   72        1          2        0     5715        0     0        1   17   
45209   57        1          2        0      668        0     0        2   17   
45210   37        1          2        0     2971        0     0        1   17   

       duration  ...  month_dec  month_feb  month_jan month_jul month_jun  \
0           261  ...          0          0          0         0         0   
1           151  ...          0          0          0         0         0   
2            76  ...          0          0          0         0         0   
3            92  ...          0          0          0         0         0   
4           198  ...          0          0          0         0         0   
...         ...  ...        ...        ...        ...       ...       ...   
45206       977  ...          0          0          0         0         0   
45207       456  ...          0          0          0         0         0   
45208      1127  ...          0          0          0         0         0   
45209       508  ...          0          0          0         0         0   
45210       361  ...          0          0          0         0         0   

       month_mar  month_may  month_nov  month_oct  month_sep  
0              0          1          0          0          0  
1              0          1          0          0          0  
2              0          1          0          0          0  
3              0          1          0          0          0  
4              0          1          0          0          0  
...          ...        ...        ...        ...        ...  
45206          0          0          1          0          0  
45207          0          0          1          0          0  
45208          0          0          1          0          0  
45209          0          0          1          0          0  
45210          0          0          1          0          0  

[45211 rows x 37 columns]

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 37 columns):
 #   Column             Non-Null Count  Dtype 
---  ------             --------------  ----- 
 0   age                45211 non-null  int64 
 1   marital            45211 non-null  int64 
 2   education          45211 non-null  int64 
 3   default            45211 non-null  int64 
 4   balance            45211 non-null  int64 
 5   housing            45211 non-null  int64 
 6   loan               45211 non-null  int64 
 7   contact            45211 non-null  int64 
 8   day                45211 non-null  int64 
 9   duration           45211 non-null  int64 
 10  campaign           45211 non-null  int64 
 11  pdays              45211 non-null  int64 
 12  previous           45211 non-null  int64 
 13  poutcome           45211 non-null  object
 14  y                  45211 non-null  object
 15  job_blue-collar    45211 non-null  uint8 
 16  job_entrepreneur   45211 non-null  uint8

In [22]:
df['poutcome'].value_counts().to_dict()

{'unknown': 36959, 'failure': 4901, 'other': 1840, 'success': 1511}

In [23]:
df['poutcome'].replace({'unknown': 1, 'failure': 0, 'other': 2, 'success': 3},inplace=True)

In [24]:
df['y'].value_counts().to_dict()

{'no': 39922, 'yes': 5289}

In [25]:
df['y'].replace({'no': 0, 'yes': 1},inplace=True)

In [26]:
x=df.drop('y',axis=1)
y=df['y']

In [27]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=10)

In [28]:
Log_model=LogisticRegression()
Log_model.fit(x_train,y_train)

C:\Users\mahes\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:814: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [29]:
# Training 

y_pred_train=Log_model.predict(x_train)

acc_value=accuracy_score(y_train,y_pred_train)
print("Accuracy score",acc_value)

cnf_matrix=confusion_matrix(y_train,y_pred_train)
print("COnfusion matrix\n",cnf_matrix)

classification_value=classification_report(y_train,y_pred_train)
print("Classification report \n",classification_value)

Accuracy score 0.8859291560021487
COnfusion matrix
 [[27348   568]
 [ 3042   689]]
Classification report 
               precision    recall  f1-score   support

           0       0.90      0.98      0.94     27916
           1       0.55      0.18      0.28      3731

    accuracy                           0.89     31647
   macro avg       0.72      0.58      0.61     31647
weighted avg       0.86      0.89      0.86     31647



In [30]:
# Testing 

y_pred_test=Log_model.predict(x_test)

acc_value=accuracy_score(y_test,y_pred_test)
print("Accuracy score",acc_value)

cnf_matrix=confusion_matrix(y_test,y_pred_test)
print("COnfusion matrix\n",cnf_matrix)

classification_value=classification_report(y_test,y_pred_test)
print("Classification report \n",classification_value)

Accuracy score 0.8880123857269242
COnfusion matrix
 [[11739   267]
 [ 1252   306]]
Classification report 
               precision    recall  f1-score   support

           0       0.90      0.98      0.94     12006
           1       0.53      0.20      0.29      1558

    accuracy                           0.89     13564
   macro avg       0.72      0.59      0.61     13564
weighted avg       0.86      0.89      0.86     13564



In [32]:
# By using decision tree

dec_model=DecisionTreeClassifier()
dec_model.fit(x_train,y_train)

DecisionTreeClassifier()

In [33]:
# Training 

y_pred_train=dec_model.predict(x_train)

acc_value=accuracy_score(y_train,y_pred_train)
print("Accuracy score",acc_value)

cnf_matrix=confusion_matrix(y_train,y_pred_train)
print("COnfusion matrix\n",cnf_matrix)

classification_value=classification_report(y_train,y_pred_train)
print("Classification report \n",classification_value)

Accuracy score 1.0
COnfusion matrix
 [[27916     0]
 [    0  3731]]
Classification report 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     27916
           1       1.00      1.00      1.00      3731

    accuracy                           1.00     31647
   macro avg       1.00      1.00      1.00     31647
weighted avg       1.00      1.00      1.00     31647



In [34]:
# Testing 

y_pred_test=dec_model.predict(x_test)

acc_value=accuracy_score(y_test,y_pred_test)
print("Accuracy score",acc_value)

cnf_matrix=confusion_matrix(y_test,y_pred_test)
print("COnfusion matrix\n",cnf_matrix)

classification_value=classification_report(y_test,y_pred_test)
print("Classification report \n",classification_value)

Accuracy score 0.8728251253317605
COnfusion matrix
 [[11088   918]
 [  807   751]]
Classification report 
               precision    recall  f1-score   support

           0       0.93      0.92      0.93     12006
           1       0.45      0.48      0.47      1558

    accuracy                           0.87     13564
   macro avg       0.69      0.70      0.70     13564
weighted avg       0.88      0.87      0.87     13564



In [35]:
hyper_parametrs={"criterion":['gini','entropy'],"max_depth": np.arange(3,9),
                 "min_samples_split":np.arange(2,20),"min_samples_leaf": np.arange(2,10)}

In [36]:
gscv_dt_model=RandomizedSearchCV(dec_model,hyper_parametrs,cv=5)
gscv_dt_model.fit(x_train,y_train)
gscv_dt_model.best_estimator_

DecisionTreeClassifier(max_depth=3, min_samples_leaf=8, min_samples_split=12)

In [37]:
dt_model=DecisionTreeClassifier(max_depth=3, min_samples_leaf=9, min_samples_split=10)
dt_model.fit(x_train,y_train)
 

DecisionTreeClassifier(max_depth=3, min_samples_leaf=9, min_samples_split=10)

In [38]:
# Training 

y_pred_train=dt_model.predict(x_train)

acc_value=accuracy_score(y_train,y_pred_train)
print("Accuracy score",acc_value)

cnf_matrix=confusion_matrix(y_train,y_pred_train)
print("COnfusion matrix\n",cnf_matrix)

classification_value=classification_report(y_train,y_pred_train)
print("Classification report \n",classification_value)

Accuracy score 0.9002117104306885
COnfusion matrix
 [[27247   669]
 [ 2489  1242]]
Classification report 
               precision    recall  f1-score   support

           0       0.92      0.98      0.95     27916
           1       0.65      0.33      0.44      3731

    accuracy                           0.90     31647
   macro avg       0.78      0.65      0.69     31647
weighted avg       0.88      0.90      0.89     31647



In [39]:
# Testing 

y_pred_test=dt_model.predict(x_test)

acc_value=accuracy_score(y_test,y_pred_test)
print("Accuracy score",acc_value)

cnf_matrix=confusion_matrix(y_test,y_pred_test)
print("COnfusion matrix\n",cnf_matrix)

classification_value=classification_report(y_test,y_pred_test)
print("Classification report \n",classification_value)

Accuracy score 0.9021675022117369
COnfusion matrix
 [[11709   297]
 [ 1030   528]]
Classification report 
               precision    recall  f1-score   support

           0       0.92      0.98      0.95     12006
           1       0.64      0.34      0.44      1558

    accuracy                           0.90     13564
   macro avg       0.78      0.66      0.69     13564
weighted avg       0.89      0.90      0.89     13564

